"""Workshop supply budget. Prices as seen on supplier pages 2026-09-28 (see compendium ch. 6).
Edit PARTICIPANTS and the assumptions, then run: python3 budget.py > supply-budget.md"""
PARTICIPANTS = 10
# --- UK route A: one Cornelissen complete set per person + extras (GBP)
kit_per_person = 55.00            # cornelissen-set
extra_ply_per_person = 2 * 1.30   # 2 x economy shina ply, handprinted-japanese ("from" price)
nori_shared = 3 * 1.30            # 3 tubs/packs nori, handprinted-japanese ("from" price)
camellia_oil_shared = 16.30       # handprinted-japanese
# --- UK route B: assemble a minimal set per person (GBP)
hangito = 31.00                   # handprinted-japanese
u_gouge = 32.00                   # handprinted-japanese
plastic_baren = 6.90              # handprinted-japanese
brushes = 2 * 6.80                # 2 inking brushes "from", handprinted-japanese
watercolour_set_shared = 35.00    # upper end of handprinted watercolour sets, one per 4 people
# --- Paper (USD, Hiromi). Sheet size varies by paper; ASSUMPTION: 1 full sheet yields 8 postcard/A5 prints
paper_per_sheet_usd = 19.00       # Yamada Hanga, hiromi-sized-papers
prints_per_person = 12            # proofs + small edition
prints_per_sheet = 8              # ASSUMPTION - check real sheet size before ordering

import math
tables = math.ceil(PARTICIPANTS / 4)
a_pp = kit_per_person + extra_ply_per_person
a_total = a_pp * PARTICIPANTS + nori_shared + camellia_oil_shared
b_pp = hangito + u_gouge + plastic_baren + brushes + extra_ply_per_person
b_total = b_pp * PARTICIPANTS + nori_shared + camellia_oil_shared + watercolour_set_shared * tables
sheets = math.ceil(PARTICIPANTS * prints_per_person / prints_per_sheet)
paper_usd = sheets * paper_per_sheet_usd

print(f"# Supply budget ({PARTICIPANTS} participants)\n")
print("Generated by `budget.py` from prices seen on supplier pages on 2026-09-28 (compendium ch. 6). Prices change; re-check before ordering. Shipping, VAT/tax and your own tools are not included.\n")
print("| Route | Per person | Class total | Notes |\n|---|---|---|---|")
print(f"| A. UK kit (Cornelissen set + 2 extra shina blocks) | £{a_pp:.2f} | £{a_total:.2f} | + shared nori and camellia oil. Participants keep a full starter set |")
print(f"| B. UK assembled (Handprinted: hangi-tō, U-gouge, plastic baren, 2 brushes, 2 blocks) | £{b_pp:.2f} | £{b_total:.2f} | + {tables} shared watercolour sets. Better knife, no aisuki; add one if the budget allows |")
print(f"\n**Paper:** {sheets} sheets of sized hanga paper at ${paper_per_sheet_usd:.2f} = **${paper_usd:.2f}** "
      f"(assumes {prints_per_person} prints per person and {prints_per_sheet} prints per sheet; check the real sheet size).\n")
print("**Teacher's shared kit (not costed):** kento chisel, wide gouges, sharpening stone, one ball-bearing baren to try "
      "(Kean ~$175–185 / from £108), first-aid kit, spray bottles, newsprint, plastic sheeting, drying blotters.\n")
print("**US note:** McClain's printing kit ($248.85) has no carving knives and is priced for one person. For a US class, price "
      "McClain's student tool grades per person, plus a shared printing kit per table. Individual McClain's tool prices were not captured this session.")
